export 'package:flutter/material.dart';
export 'package:flutter_riverpod/flutter_riverpod.dart';
export 'package:google_fonts/google_fonts.dart';
export 'package:littlefont/Screens/AboutPage/about_page.dart';
export 'package:littlefont/Screens/CategoryPage/category_page.dart';
export 'package:littlefont/Screens/FavouritesPage/favourites_page.dart';
export 'package:littlefont/Screens/FirstScreenPage/first_screen.dart';
export 'package:littlefont/Screens/MyNotesPage/my_notes_page.dart';
export 'package:littlefont/Screens/RecycleBinPage/recycle_bin_page.dart';