// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3NOKTExFvoOB--secYvQ7r32_OVu4NUc',
    appId: '1:300282932986:web:b5bf0071e0eebe2654a343',
    messagingSenderId: '300282932986',
    projectId: 'littlefont-3ee9b',
    authDomain: 'littlefont-3ee9b.firebaseapp.com',
    databaseURL: 'https://littlefont-3ee9b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'littlefont-3ee9b.appspot.com',
    measurementId: 'G-04TBK0BWRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJQIn3m-knMjRiOFnV0Au9IQ6MUJBge3E',
    appId: '1:300282932986:android:3265ef8f96b66c4154a343',
    messagingSenderId: '300282932986',
    projectId: 'littlefont-3ee9b',
    databaseURL: 'https://littlefont-3ee9b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'littlefont-3ee9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv14iI9Q-6X59Ml4CYsjgKH_uSObuL7WM',
    appId: '1:300282932986:ios:4403a6bc2b6321ad54a343',
    messagingSenderId: '300282932986',
    projectId: 'littlefont-3ee9b',
    databaseURL: 'https://littlefont-3ee9b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'littlefont-3ee9b.appspot.com',
    androidClientId: '300282932986-200jpo6bc5jr88hgnu91i2rr7v5a4516.apps.googleusercontent.com',
    iosClientId: '300282932986-763moi77vkbaia9bt33vr8kqpndajiju.apps.googleusercontent.com',
    iosBundleId: 'com.example.littlefont',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv14iI9Q-6X59Ml4CYsjgKH_uSObuL7WM',
    appId: '1:300282932986:ios:4403a6bc2b6321ad54a343',
    messagingSenderId: '300282932986',
    projectId: 'littlefont-3ee9b',
    databaseURL: 'https://littlefont-3ee9b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'littlefont-3ee9b.appspot.com',
    androidClientId: '300282932986-200jpo6bc5jr88hgnu91i2rr7v5a4516.apps.googleusercontent.com',
    iosClientId: '300282932986-763moi77vkbaia9bt33vr8kqpndajiju.apps.googleusercontent.com',
    iosBundleId: 'com.example.littlefont',
  );
}
