// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn2SpIunsFVDvZ7gVLGtB8TvG8pK8TYg8',
    appId: '1:1007734945620:web:8a5422560ec32ded1f3ac1',
    messagingSenderId: '1007734945620',
    projectId: 'littlefontapp',
    authDomain: 'littlefontapp.firebaseapp.com',
    storageBucket: 'littlefontapp.appspot.com',
    measurementId: 'G-CED2E0KY95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCASTQshdHs4KEmJCfCowgCN7GZLAQHHwQ',
    appId: '1:1007734945620:android:615f60289d2326c31f3ac1',
    messagingSenderId: '1007734945620',
    projectId: 'littlefontapp',
    storageBucket: 'littlefontapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgk3dLdjqM_V0Jq-v6ErhyHK0z_0CrGm0',
    appId: '1:1007734945620:ios:4f10ca514d35f0621f3ac1',
    messagingSenderId: '1007734945620',
    projectId: 'littlefontapp',
    storageBucket: 'littlefontapp.appspot.com',
    iosClientId: '1007734945620-mrn1s9vki47dobatqoemtudcg58id11e.apps.googleusercontent.com',
    iosBundleId: 'com.example.littlefontApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgk3dLdjqM_V0Jq-v6ErhyHK0z_0CrGm0',
    appId: '1:1007734945620:ios:d9ec3753d8a265181f3ac1',
    messagingSenderId: '1007734945620',
    projectId: 'littlefontapp',
    storageBucket: 'littlefontapp.appspot.com',
    iosClientId: '1007734945620-o58h8fk7efipnu31pin2odpkk1oqk304.apps.googleusercontent.com',
    iosBundleId: 'com.example.littlefontApp.RunnerTests',
  );
}
